{{- $host := ternary (eq .Env "ai") (printf "dev-%d.%s" .Slot (index .BaseDomain "ai")) (index .BaseDomain .Env) -}}
{{- $registryHost := envOr "CODEXCTL_REGISTRY_HOST" (printf "registry.%s-ai-staging.svc.cluster.local:5000" .Project) -}}
{{- $tagEnv := ternary (eq .Env "ai") "ai-staging" .Env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-frontend-config
  namespace: {{ .Namespace }}
data:
  SERVICE_NAME: "web-frontend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      {{- if eq .Env "ai" }}
      securityContext:
        fsGroup: {{ envOr "CODEXCTL_WORKSPACE_GID" "1000" }}
      {{- end }}
      containers:
        - name: web-frontend
          image: {{ $registryHost }}/project-example/web-frontend:{{ $tagEnv }}-{{ index .Versions "web-frontend" }}
          command:
            - sh
            - -c
            - >-
              if [ ! -x /app/node_modules/.bin/vite ]; then
                npm install --no-package-lock;
              fi;
              exec npm run dev -- --host 0.0.0.0 --port 5173
          ports:
            - containerPort: 5173
          {{- if or (eq .Env "ai") (eq .Env "ai-staging") }}
          securityContext:
            runAsUser: {{ envOr "CODEXCTL_WORKSPACE_UID" "1000" }}
            runAsGroup: {{ envOr "CODEXCTL_WORKSPACE_GID" "1000" }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: HOME
              value: "/tmp"
            - name: NPM_CONFIG_CACHE
              value: "/tmp/npm-cache"
            - name: VITE_ALLOWED_HOSTS
              value: "{{ $host }}"
          envFrom:
            - configMapRef:
                name: web-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: {{ .Namespace }}
spec:
  selector:
    app: web-frontend
  ports:
    - name: http
      port: 80
      targetPort: 5173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-frontend-ingress
  namespace: {{ .Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $host }}
      secretName: project-example-tls
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  number: 80
