run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  revive:
    ignore-generated-header: true
    rules:
      - name: blank-imports
      - name: early-return
      - name: error-return
      - name: error-strings
      - name: if-return
      - name: range-val-in-closure
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return

