version: 2

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  staticcheck:
    # В этом проекте мы избегаем warning-шума по deprecations (особенно в коде инфраструктуры/observability),
    # но оставляем остальные проверки.
    checks: ["all", "-SA1019"]
