{{- $host := ternary (eq .Env "ai") (printf "dev-%d.%s" .Slot (index .BaseDomain "ai")) (index .BaseDomain .Env) -}}
{{- $registryHost := envOr "CODEXCTL_REGISTRY_HOST" (printf "registry.%s.svc.cluster.local:5000" .Namespace) -}}
{{- $tagEnv := ternary (eq .Env "ai") "ai-staging" .Env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-web-config
  namespace: {{ .Namespace }}
data:
  SERVICE_NAME: "chat-web"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-web
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-web
  template:
    metadata:
      labels:
        app: chat-web
    spec:
      containers:
        - name: chat-web
          image: {{ $registryHost }}/project-example/chat-web:{{ $tagEnv }}-{{ index .Versions "chat-web" }}
          ports:
            - containerPort: 5173
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: HOME
              value: "/tmp"
            - name: NPM_CONFIG_CACHE
              value: "/tmp/npm-cache"
            - name: VITE_ALLOWED_HOSTS
              value: "{{ $host }}"
          envFrom:
            - configMapRef:
                name: chat-web-config
---
apiVersion: v1
kind: Service
metadata:
  name: chat-web
  namespace: {{ .Namespace }}
spec:
  selector:
    app: chat-web
  ports:
    - name: http
      port: 80
      targetPort: 5173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-web-ingress
  namespace: {{ .Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $host }}
      secretName: project-example-tls
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-web
                port:
                  number: 80

