{{- $registryHost := envOr "CODEXCTL_REGISTRY_HOST" (printf "registry.%s.svc.cluster.local:5000" .Namespace) -}}
{{- $host := ternary (eq .Env "ai") (printf "dev-%d.%s" .Slot (index .BaseDomain "ai")) (index .BaseDomain .Env) -}}
{{- $tagEnv := ternary (eq .Env "ai") "ai-staging" .Env -}}
{{- $workspacePVC := envOr "CODEXCTL_WORKSPACE_PVC" (printf "%s-workspace" .Project) -}}
{{- $workspaceMount := envOr "CODEXCTL_WORKSPACE_MOUNT" "/workspace" -}}
{{- $codeRootBase := envOr "CODEXCTL_CODE_ROOT_BASE" (printf "%s/codex/envs" $workspaceMount) -}}
{{- $codeRoot := ternary (eq .Env "ai") (printf "%s/%d/src" $codeRootBase .Slot) (ternary (or (eq .Env "ai-staging") (eq .Env "ai-repair")) (printf "%s/ai-staging/src" $codeRootBase) (printf "%s/dev/src" $codeRootBase)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-gateway-config
  namespace: {{ .Namespace }}
data:
  SERVICE_NAME: "chat-gateway"
  HTTP_PORT: "8080"
  CODE_ROOT: "{{ $codeRoot }}"
  USERS_GRPC_ADDR: "users:8080"
  MESSAGES_GRPC_ADDR: "messages:8080"
  COOKIE_NAME: "sid"
  COOKIE_MAX_AGE_SECONDS: "86400"
  COOKIE_SECURE: "true"
  ENV_PREFIX: "CHAT_GATEWAY_"
  TZ: "UTC"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-gateway
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-gateway
  template:
    metadata:
      labels:
        app: chat-gateway
    spec:
      initContainers:
        - name: wait-for-users
          image: {{ $registryHost }}/library/busybox:{{ index .Versions "busybox" }}
          command: ["sh", "-c", "until nc -zw1 users 8080; do echo 'waiting for users'; sleep 2; done"]
        - name: wait-for-messages
          image: {{ $registryHost }}/library/busybox:{{ index .Versions "busybox" }}
          command: ["sh", "-c", "until nc -zw1 messages 8080; do echo 'waiting for messages'; sleep 2; done"]
        - name: wait-for-redis
          image: {{ $registryHost }}/library/busybox:{{ index .Versions "busybox" }}
          command: ["sh", "-c", "until nc -zw1 redis 6379; do echo 'waiting for redis'; sleep 2; done"]
      containers:
        - name: chat-gateway
          image: {{ $registryHost }}/project-example/external/chat-gateway:{{ $tagEnv }}-{{ index .Versions "chat-gateway" }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /health/livez
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: HOME
              value: "/tmp"
            - name: GOCACHE
              value: "/tmp/go-build-cache"
            - name: GOMODCACHE
              value: "/tmp/go-mod-cache"
            - name: GOPATH
              value: "/tmp/go"
          envFrom:
            - secretRef:
                name: redis-secret
            - configMapRef:
                name: project-example-config
            - configMapRef:
                name: redis-config
            - configMapRef:
                name: chat-gateway-config
          volumeMounts:
            - name: workspace
              mountPath: {{ $workspaceMount }}
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ $workspacePVC }}
---
apiVersion: v1
kind: Service
metadata:
  name: chat-gateway
  namespace: {{ .Namespace }}
spec:
  selector:
    app: chat-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-gateway-ingress
  namespace: {{ .Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $host }}
      secretName: project-example-tls
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-gateway
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: chat-gateway
                port:
                  number: 8080
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: chat-gateway
                port:
                  number: 8080
